## comparison operators


In [1]:
2<3

True

It is also possible to compare strings. 

In [9]:
'carl' < 'chris'

True

Boolean vs integer

In [3]:
True == 1  # False == 0. In this way, True > False. 

True

Compare arrays

In [8]:
import numpy as np
array1 = np.array([18, 3, 5])
print (array1 >= 18)

[ True False False]


In [10]:
array2 = np.array([19, 4, 2])
print (array1 < array2)

[ True  True False]


## Booleans

In [13]:
True and True
# True and False

True

`logical_and(), logical_or(), logical_not()` is an alternative for series. 

In [14]:
np.logical_and(array1 >10, array1 < 20)  # combine more than 1 conditions

array([ True, False, False])

## if, elif, else
remember the colon! 

In [15]:
z = 3
if z % 2 == 0:
    print ('z is divisible by 2')
elif z % 3 == 0:
    print ('z is divisible by 3')
else: 
    print ('else')
    

z is divisible by 3


## while

To stop: ctl+C

In [17]:
x = 1
while x < 4 :
    print(x)
    x = x + 1

1
2
3


## For 

Use `enumerate()` to get both index and value for a series. 

In [18]:
# areas list
areas = [11.25, 18.0, 20.0, 10.75, 9.50]
# enumerate(areas)
for a, b in enumerate(areas) :
    print('room' + str(a) + ':' + str(b))    # use a+1 to start from1. 

room0:11.25
room1:18.0
room2:20.0
room3:10.75
room4:9.5


When there's list over list, can do the same. 

In [19]:
# house list of lists
house = [["hallway", 11.25], 
         ["kitchen", 18.0], 
         ["living room", 20.0], 
         ["bedroom", 10.75], 
         ["bathroom", 9.50]]
         
for room in house:
    print ('the ' + str(room[0]) + ' is ' + str(room[1]) + ' sqm')   # note that float has to be convert to string. 

the hallway is 11.25 sqm
the kitchen is 18.0 sqm
the living room is 20.0 sqm
the bedroom is 10.75 sqm
the bathroom is 9.5 sqm


# Loop data structures 

## 1. dictionary
use `.items()` in loops. It is a **method**. 

In [1]:
world = {
    'afghanistan': 30.55, 
    'albania': 2.77, 
    'algeria': 39.21
}
for key, value in world.items():
    print (key + '--' + str(value))

afghanistan--30.55
albania--2.77
algeria--39.21


## 2. numpy array
very simple if loop over a 1D array. 

For more than 1D, use `np.nditer(my_array)`, which is a **function** instead of **method**. 

In [3]:
import numpy as np
np_array1 = np.array([1,2,3])
np_array2 = np.array([4,5,6])
meas = np.array([np_array1, np_array2]) # this gives a list of 2 arrays
print (meas)

[[1 2 3]
 [4 5 6]]


In [9]:
meas.size  # this gives 6, the total elements

6

In [10]:
meas.shape # (2, 3), indicating 2 rows 3 cols

(2, 3)

In [11]:
for val in meas:    # so each row is a value in meas. 
    print(val)

[1 2 3]
[4 5 6]


In [12]:
for val in np.nditer(meas):  # this prints first array1, then array2
    print(val)

1
2
3
4
5
6


## 3. DataFrame

In [13]:
import pandas as pd
brics = pd.read_csv('brics.csv', index_col = 0) # the first column is treated as row index. (can be arbitrary)
brics

country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Delhi   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98

In [14]:
for i in brics:   # this prints the column names 
    print (i)

country
capital
area
population


In [18]:
for label, row in brics.iterrows():
    print (label)
    print (row)

country         Brazil
capital       Brasilia
area             8.516
population       200.4
Name: BR, dtype: object
country       Russia
capital       Moscow
area            17.1
population     143.5
Name: RU, dtype: object
country           India
capital       New Delhi
area              3.286
population         1252
Name: IN, dtype: object
country         China
capital       Beijing
area            9.597
population       1357
Name: CH, dtype: object
country       South Africa
capital           Pretoria
area                 1.221
population           52.98
Name: SA, dtype: object


In [23]:
for label, row in brics.iterrows():
    print (label + ':' + row['capital'])  # equivalent to row[1] 

BR:Brasilia
RU:Moscow
IN:New Delhi
CH:Beijing
SA:Pretoria


In [24]:
for label, row in brics.iterrows():
    brics.loc[label, 'name_length'] = len(row['country'])  # adds a col that counts the length of countryname
    
print (brics)

# brics.loc['BR', 'capital']   first index is the label of row. second is the column wanted. 

         country    capital    area  population  name_length
BR        Brazil   Brasilia   8.516      200.40          6.0
RU        Russia     Moscow  17.100      143.50          6.0
IN         India  New Delhi   3.286     1252.00          5.0
CH         China    Beijing   9.597     1357.00          5.0
SA  South Africa   Pretoria   1.221       52.98         12.0


Or, use `apply()`. 

In [27]:
brics['name_length2'] = brics['country'].apply(len)  # same thing. 
print (brics)

         country    capital    area  population  name_length  name_length2
BR        Brazil   Brasilia   8.516      200.40          6.0             6
RU        Russia     Moscow  17.100      143.50          6.0             6
IN         India  New Delhi   3.286     1252.00          5.0             5
CH         China    Beijing   9.597     1357.00          5.0             5
SA  South Africa   Pretoria   1.221       52.98         12.0            12


When it's not a function but a method, use `.apply(str.method)`

In [28]:
brics['COUNTRY'] = brics['country'].apply(str.upper)
print (brics)

         country    capital    area  population  name_length  name_length2  \
BR        Brazil   Brasilia   8.516      200.40          6.0             6   
RU        Russia     Moscow  17.100      143.50          6.0             6   
IN         India  New Delhi   3.286     1252.00          5.0             5   
CH         China    Beijing   9.597     1357.00          5.0             5   
SA  South Africa   Pretoria   1.221       52.98         12.0            12   

         COUNTRY  
BR        BRAZIL  
RU        RUSSIA  
IN         INDIA  
CH         CHINA  
SA  SOUTH AFRICA  
